#!/bin/bash

if [ "$#" -ne 1 ] ; then
  echo "Usage: $0 \"<title>\"" >&2
  exit 1
fi

filename="_posts/`date +%Y-01-01-00-"${1}".markdown`"
filename=${filename//" "/"_"}

cat > $filename <<PTEMPLATE
---
layout: post
title: 
category: ""
---

PTEMPLATE

vim ${filename}
